# Generated by Django 5.0 on 2023-12-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_result_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiztype/'),
        ),
    ]
