name: Quiz Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  first:
    name: Install ubuntu
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 2002
          POSTGRES_DB: quizdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Update
        run: sudo apt update
      - name: check out repo
        uses: actions/checkout@v3
      - name: Install python3-pip
        run: sudo apt install python3-pip
      - name: Requirements install
        run: pip install -r requirements.txt
      - name: Run test
        env:
          DJANGO_SETTINGS_MODULE: QuizProject.settings.local
          SQL_ENGINE: django.db.backends.postgresql
          SQL_DATABASE: quizdb
          SQL_USER: postgres
          SQL_PASSWORD: 2002
          SQL_HOST: localhost
          SQL_PORT: 5432
        run: python manage.py test